[package]
name = "toby-plugin"
version = "0.1.0"
authors = ["Ruben Schmidmeister <ruben.schmidmeister@icloud.com>"]
edition = "2018"

[dependencies]
toby-core = { path = "../toby-core" }
serde = "1.0"
