sudo: false
dist: trusty
language: rust

cache:
  directories:
  - "$HOME/.cargo"

  rust:
- nightly

notifications:
  email: false

  addons:
    apt:
      packages:
      - rpm

deploy:
  provider: releases
  api_key:
    secure: nw7rtByvp81nag1bQ7uz6lJchAn8HfZBQ/sw1rctFJyLIkLZ3vc/kMNEW65gNmCVyNewLZ6OFdLXnqjxSOgSrUXcdJl+acpRu3ftf6dp2Ir8BEs+ZDB8l8AqPRP8pRSf2PAZ8+Q+rOYpeq0CnaSTjn4nrl0UlNjkeXQn2f7D0YYnkYDkXE3s4OGYxhxNQq4DIaXKWhDGCQQa9z2mdJlmeUXZf4jgrx2Pf//tsKOTyz4vcrjJ5HX+jKwdLxBsH8OVeje3XV247IjxIAIHXJFfF/8Lb3JiU3mzIgK0W2hNyaYxGuJORdEP715ipoMQGQqPN9WdpICFFw97EB8qAVcY4PRdrg2rXHjjLk22CYXuxN9cIeGxCMocQ+qfoEScV0N/7uK9ZtfKhdPZG9EyyaTCw9I7WgsP4f4LnsYTzdyKx9UXM+Fg1EwkQrcc95EU+dSuGsZj1TiL/S5XSL8qH4PmlL4iVjRrAhwSWHnwPdceS/jK5mU5WvslynucqlSh9gwxjxzVMqfza5mOj0VqCU57YiFNKWT5HHCgtfTBZh9Fxmt+DYzOAkba99rNxmEqhLyNnrO7nUvc4K42hW+9Gw5Nk1DXJ1wiHqcaRvOJ+sdJ+a+QtfGnnqsxnhhJfvv7Y6NTo82VVbj4YOVCO/5IhnsrXN6Q+rQ4Hz6UyWl/SbYnLzY=
  file: "$HOME/rpmbuild/RPMS/x86_64/*.rpm"
  file_glob: true
  on:
    repo: bash/toby
    tags: true
