[package]
name = "toby-workerd"
version = "0.1.0"
authors = ["Ruben Schmidmeister <ruben.schmidmeister@icloud.com>"]
edition = "2018"

[dependencies]
toby-core = { path = "../toby-core" }
toby-worker = { path = "../toby-worker" }
tokio = "0.1"
futures = "0.1"

[features]
enable-user-switch = []
