cargo-features = ["edition"]

[package]
name = "toby-telegram"
version = "0.1.0"
authors = ["Ruben Schmidmeister <ruben.schmidmeister@icloud.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
toby-plugin = { path = "../toby-plugin" }
serde = "1.0"
serde_derive = "1.0"
