# Changes the address and port the http servers listens on.
# [listen]
# address = "0.0.0.0"
# port = 8629

# Although not required it is recommended to enable TLS.
# [tls]
# certificate = "/etc/letsencrypt/live/toby.friendly/fullchain.pem"
# certificate_key = "/etc/letsencrypt/live/toby.friendly/privkey.pem"

# The bot can notify you about success/failure of jobs through telegram.
# [telegram]
# token = "TOKEN"

# The slack bot can notify you about success/failure through slack.
# [slack]
# bot_token = "BOT_TOKEN"
# channel = "#general"
