# Changes the address and port the http servers listens on.
# [listen]
# address = "0.0.0.0"
# port = 8629

# The bot can notify you about success/failure of jobs through telegram.
# [telegram]
# token = "TOKEN"
# chat_id = "CHAT_ID"
