# This file contains tokens that give access
# for triggering jobs through webhooks.

# An example config looks like this:
# to generate a random secret run `toby gen-secret`
# [travis]
# secret = "SECRET"
# access = ["PROJECT_1", "PROJECT_2"]
