[package]
name = "toby-core"
version = "0.1.0"
authors = ["Ruben Schmidmeister <ruben.schmidmeister@icloud.com>"]
publish = false

[dependencies]
bincode = "1.0"
serde = "1.0"
serde_derive = "1.0"
lazy_static = "1.1.0"

[dev-dependencies]
tempdir = "0.3"