cargo-features = ["edition"]

[package]
name = "toby-httpd"
version = "0.1.0"
authors = ["Ruben Schmidmeister <ruben.schmidmeister@icloud.com>"]
publish = false
edition = "2018"

[dependencies]
toby-core = { path = "../toby-core" }

[features]
enable-user-switch = []
